services:
  libraryservice.api:
    image: libraryserviceapi  
    build:
      context: .  
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 
      - ConnectionStrings__DefaultConnection=Host=library.db;Database=user-database;Username=postgres;Password=pass
    volumes:
      - library_keys:/app/keys  
    ports:
      - "8080:8080" 
    depends_on:
      - library.db
    
  library.db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=user-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  library_keys: