services:
  libraryservice.api:
    image: ${DOCKER_REGISTRY-}libraryserviceapi
    build:
      context: Library/LibraryService.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  library.db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=user-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432

